# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='visit_time',
        ),
    ]
