# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160815_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodwork',
            name='reading',
            field=models.IntegerField(default='0'),
        ),
    ]
